name = "lako-services"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2026-05-27"
compatibility_flags = ["nodejs_compat", "disable_nodejs_process_v2"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"

[vars]
LAKO_BOT_API_URL = "https://bot.lako.services"

[observability]
enabled = true
